### ISSUE TITLE
Community Sentiment should show total number of votes cast for each sentiment

### ISSUE THREAD

**Issue by rahme-butaineh** [Call-for-Code-for-Racial-Justice/Truth-Loop#107]
Community Sentiment should show total number of votes cast for each sentiment, as well as total number of votes cast. Percentages alone are not a good enough indicator of public feeling. By showing total votes, the user could see how active the community is on a particular piece of legislation.

**Comment by Sabine-Justilien** [comment]
During a design thinking session a Rating system (by Citizens) for the most persuasive arguments was recommended. More investigation on voting and rating option as sentiment mechanisms is needed.
