### ISSUE TITLE
replace vue with react in readme

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Truth-Loop#140]
@markstur should we remove vue from README now that the app has migrated to react?

FYI @demilolu

**Comment by markstur** [comment]
not yet.  We have only started the react migration.  It isn't done yet.

**Comment by upkarlidder** [comment]
Thank you @LucasRobs. I added this as a simple markdown change. The team is moving from vue.js to react.js. The readme still refers to vue. However, as @markstur, the effort is still ongoing. Would you like to help with that effort?

@markstur appreciate your feedback here.

**Comment by markstur** [comment]
> Thank you @LucasRobs. I added this as a simple markdown change. The team is moving from vue.js to react.js. The readme still refers to vue. However, as @markstur, the effort is still ongoing. Would you like to help with that effort?
> 
> @markstur appreciate your feedback here.

Merged PR #183 last night so please go ahead and make the README.md and architecture/flow diagram not show vue.js but show React.js instead.

Regarding help to complete the migration there are additional issues discussing some ToDos, and another migration for the Admin UI (which is separate from client/).

**Comment by LucasRobs** [comment]
I created two impetuous ones because I was fixing the name of the first one, I accidentally put it wrong.

**Comment by ed-snodgrass** [comment]
This has been completed.
