### ISSUE TITLE
Get routing functioning to the 3 components that are currently available (Home, Policy, Record)

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#142]
The Home, Policy, and Record routes & components are not currently set up in the react application. This ticket is just get the routing set up (and tested). The components can be empty components, as little as necessary to get the routing stood up.

- [x] Route to Home
- [x] Route to Policy
- [x] Route to Record
- [x] Unit tests for routing

**Comment by eis95** [comment]
@markstur Should we add a label for the `react-transition`?

**Comment by markstur** [comment]
Good idea @eis95. I added a React label. I kept it more general than react-transition because that seemed sufficient for now and we can expand later if you want more labels.
