### ISSUE TITLE
React component for the AppTopBar

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#143]
We need an AppTopBar that behaves the same as the current Vue version. Along with component tests.

**Comment by felizj17** [comment]
Hello, I'm working on this now, the right panel svg currently has no function correct?

**Comment by ed-snodgrass** [comment]
> Hello, I'm working on this now, the right panel svg currently has no function correct?

I believe you are correct. I don't see that it has an onClick nor do I see anything update it outside of the component in some other fashion.

**Comment by felizj17** [comment]
> Hey Juan, @felizj17 are you participating in Hacktoberfest? This would be a good one for one of your PRs. Let me know if you'd like more info! 

Hey thanks for looking out but I already submitted a pr for this and for the filter-modal of the right panel of the apptopbar

**Comment by demilolu** [comment]
ok great can you link the PR here, so we can then close this issue out when the PR is merged. 

p.s if you'd like to join us as we plan next steps for Truth Loop you can [join us on Slack](callforcode.org/slack)[ racial-justice-truth-loop channel].  We'll be meeting this week.

**Comment by felizj17** [comment]
https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/pull/159

**Comment by demilolu** [comment]
ok perfect so we are all set all around. I'll close this issue.
