### ISSUE TITLE
Automated syncing of policy and legislation 

### ISSUE THREAD

**Issue by Sabine-Justilien** [Call-for-Code-for-Racial-Justice/Truth-Loop#166]
### Background on the problem the feature will solve/improved user experience
Create an automated way to sync policies and legislations to the application. Manually updating the site isn't sustainable throughout the year.

### Describe the solution you'd like
Auto-populate legislation from public sources 

###Technical requirements
- Data Feed from Legislator Publications
- API to track PR&L's progress in the legal system
- Backend End can link with multiple data sources, if necessary. 

### Tasks 
_Description of the development tasks needed to complete this issue, including tests, etc._

### Acceptance Criteria 
_Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate._

**Comment by demilolu** [comment]
I suggest we use Legi-Scan API like Legit-Info does.
