### ISSUE TITLE
Implement filters

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#175]
## Background
Follow up to #108 , now replace placholder issues real filter options (not "filter 1" "filter 2" etc). 

##

**Comment by markstur** [comment]
The video shows what filters could look like: 
![Screen Shot 2021-10-01 at 1 22 57 PM](https://user-images.githubusercontent.com/7129103/135681957-5c141ff5-8d26-4727-922a-b5d6743c44a4.png)

It's important to note that for something like "Location", we don't know if they are states, counties, coutries, etc... So a pull-down list should be based on the values pulled from the database.  If we think a field is not a good candidate fo a pull-down, then other types of widgets like a text box for text search or calendars for date searches would make sense.  

Carbondesignsystems might have suggestions for how to design filters.

I don't know if there exists screen shots or design wireframes for this.  If anyone can add that to the issue that'd be nice.

**Comment by demilolu** [comment]
Is this  good candidate for Hacktoberfest @markstur @ed-snodgrass ? 

@felizj17 were you planning on working on this?

**Comment by felizj17** [comment]
Yes I am why any suggestions?
