### ISSUE TITLE
Create New Issue Template

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#187]
### Background on the problem the feature will solve/improved user experience
Create a New Issue Template in the Truth Loop Repository

### Describe the solution you'd like
Add a .md file to the Github Issues Templates to create a new issue template

### Tasks 

1.  copy the text in the following link: https://raw.githubusercontent.com/Call-for-Code-for-Racial-Justice/Hacktoberfest/main/.github/ISSUE_TEMPLATE/new-issue-template.md
2. Create a new file in the Truth Loop folder: [.github/ ISSUE_TEMPLATE](https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/tree/main/.github/ISSUE_TEMPLATE)
3. Paste the copied text from above into file
4. name the file: new_issue_template.md
5. commit the change to your branch and create a pull request

### Acceptance Criteria 

- New Issue template.md file is in Truth Loop [.github/ ISSUE_TEMPLATE folder](https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/tree/main/.github/ISSUE_TEMPLATE)
- As a user, when I click "new issue" in the Truth Loop repository I see an option for the New Issue Template

**Comment by divyanshraj0408** [comment]
I would like to work on this issue, please assign me this issue for hacktoberfest.

**Comment by demilolu** [comment]
you got it.
