### ISSUE TITLE
Bug in Greetings Workflow .yml file

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#196]
**Describe the bug**
Error found in yaml for greetings.yml
https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/.github/workflows/greetings.yml
**To Reproduce**

**Expected behavior**
See line 9 here for what it should be (note the space) https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/.github/workflows/greetings.yml

**Screenshots**
line 9 is missing the appropriate indentation and space.

<img width="1020" alt="Screen Shot 2021-10-08 at 3 28 56 PM" src="https://user-images.githubusercontent.com/3202514/136626724-9b23eb2f-7862-4136-92b6-5b44ea5c0483.png">

**Comment by fawazsiddiqi** [comment]
Proposed a fix in https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/pull/216
