### ISSUE TITLE
Build out the Admin Home view in React

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#197]
### Background on the problem the feature will solve/improved user experience
Need to build out the home view to match the content the Vue.js version had.

### Describe the solution you'd like
There is already an AdminHomeRoute component. Just need to add the necessary sections:
-- Legislative Artifacts section
-- API docs section
-- Title section

### Tasks 
- mimic https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/Home.vue
-  Keep the tests up to date

### Acceptance Criteria 
- tests to verify
-- Legislative Artifacts section exists
-- API docs section exists
-- Shows appropriate title

**Comment by ed-snodgrass** [comment]
![image](https://user-images.githubusercontent.com/2425597/137318401-8b88677a-8c7c-4d8d-b8dc-22e01d339dcd.png)

**Comment by ed-snodgrass** [comment]
@Fiewor https://mui.com/components/typography/ should be some help.

**Comment by demilolu** [comment]
@Fiewor Ed is going to take this on so we can make progress on knocking it out.
