### ISSUE TITLE
Create React Admin version of AddIntersectionsTable

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#200]
The Intersections table is currently accessible from the Artifacts table. 
![image](https://user-images.githubusercontent.com/2425597/136642834-5b8bb66d-afb0-41f4-a8ad-bd7ead25d88a.png)

There is a button: 
![image](https://user-images.githubusercontent.com/2425597/136642820-77436d6c-330a-4dbc-96a8-dca96998df77.png)

This is the current view:
![image](https://user-images.githubusercontent.com/2425597/136642790-8c41c3d2-5302-4609-baf2-345f6f892da6.png)

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/components/AddIntersectionsTable.vue

**Comment by ed-snodgrass** [comment]
Anyone have concerns about changing up how we manage the "intersections"? I was thinking of just putting this on the Artifacts' edit view.

![image](https://user-images.githubusercontent.com/2425597/143306663-6f16ea83-f88a-4e39-b6a0-4bd9c9afc0ef.png)

@markstur something like this?

**Comment by markstur** [comment]
Thanks for providing nice screenshot details.  I was wondering what the old one looked like.

I knew the old one did lack something w.r.t. the workflow of how you add, then link. I think your suggestion is a step in the right direction.

In your new screenshots, I don't see them both "on the Artifacts edit view", but I'm assuming those two dialogs would both be part of one. So you could add intersections while doing the create/edit.

I think that would be an improvement. As long as you have the referential integrity DB part correct (i.e., it works), then I'd say there are no current users that would object (I wrote that first UI). So go ahead.

One little thing to keep in mind.  I was wondering... if I am entering an artifact, and the geography isn't there yet. Would it make sense to have a button to create a new geography.  I.e. add a new state called Puerto Rico.  That might be too much nested functionality but the original very relational point of view meant you'd have to leave and add this and that and then come back and link them.  It'd be real nice to do it all from here.  And to be fair, I'm saying that could be done later, but still think your suggestion looks good (I'll just miss the chain link icon).

**Comment by ed-snodgrass** [comment]
I think we're on the same page as far as putting all the "intersections" on the view. My plan was to allow have the intersections added immediately rather than an explicit "Update" or "Apply" action. The thinking behind that is because it easy to add/remove intersections so if it is accidentally added/deleted it can be corrected w/o much effort. 

With that in mind, we wouldn't be able to add/remove intersections during "Create" because there would be no artifact to intersect. That said, maybe the "Add" view doesn't go to the Table after successfully adding but instead leaves them in the edit view to continue adding intersections?

As far as adding a way to add geographies, officials, etc... on the fly, I am curious if we want to develop/maintain two different ways to accomplish the same goal. 

Good conversation for sure. I'll focus on getting all of this actually added and working then maybe we can create some issues for the workflow improvements.

**Comment by ed-snodgrass** [comment]
Tweaked the UI just a tad from the original. I'm ready to start handling the add/delete. 
![image](https://user-images.githubusercontent.com/2425597/143718490-2b73faec-208c-45ff-87e8-59d51c2f6995.png)
![image](https://user-images.githubusercontent.com/2425597/143718503-d79ee02b-3ecf-47e5-b112-426f19a03f8c.png)
