### ISSUE TITLE
Create React Admin version of Categories (tests, form, and view)

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#203]
Create a Route, Form and Table object based on the following:

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/components/CategoriesForm.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/Categories.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/CategoriesForm.vue

**Comment by markstur** [comment]
I'll do this one
