### ISSUE TITLE
Create React Admin version of Levels (tests, form, and view)

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#205]
Create a Route, Form and Table object based on the following:

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/components/LevelsForm.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/Levels.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/LevelsForm.vue

**Comment by t-bello7** [comment]
I would like to work on this issue.
