### ISSUE TITLE
Create React Admin version of Publications (tests, form, and view)

### ISSUE THREAD

**Issue by ed-snodgrass** [Call-for-Code-for-Racial-Justice/Truth-Loop#207]
Create a Route, Form and Table object based on the following:

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/components/PublicationsForm.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/Publications.vue

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/main/server/admin/src/views/PublicationsForm.vue

**Comment by markstur** [comment]
#214 gets this started with a working table

@ed-snodgrass can this issue be closed now or are you tracking more work to complete this one?

**Comment by ed-snodgrass** [comment]
@markstur and @demilolu,

I think this can be closed with the merge of #225 PR.

Thank you!
