### ISSUE TITLE
Provide more general support for different RDMS

### ISSUE THREAD

**Issue by henrynash** [Call-for-Code-for-Racial-Justice/Truth-Loop#60]
Currently we only support PostgreSQL, due to the fact that we use the pooling facility of the Postgres library. We should make this more generic so we can support multiple RDMSs. There are, for instance, lite tier versions (i.e. free) of RDMS such as MySQL and DB2 in the IBM Cloud, plus this would enable site owners from using the preferred location (i.e. cloud vendor vs local) and choice of RDMS.

**Comment by kafellenzer** [comment]
Hi Henry,

Does this affect/interact with finding a solution to Issue #95? For reference, I'm looking into Concrete5 as an alternate CMS and I'm just wondering if this would affect how we can support multiple RDMSs.

Thanks for your time!

**Comment by henrynash** [comment]
@kafellenzer I don't think adding support for an alternate CMS would affect #95 since these are different layers, storing different types of data. It is conceivable that a different CMS would change the data we stored in the RDMS, but not how we support multiple types of RDMS.
