### ISSUE TITLE
Find alternative video cms

### ISSUE THREAD

**Issue by bimsara-yasitha01** [Call-for-Code-for-Racial-Justice/Truth-Loop#95]
With the payment restrictions on Watson Media, we need to migrate to an open-source video content management system. 

The current CMS's being investigated:
- [Concrete5](https://www.concrete5.org/)
- [Elefant](https://www.elefantcms.com/)
- [Open Streaming Platform](https://openstreamingplatform.com/)
- [NodeTube](https://github.com/Videofy/nodetube)
- [Vimp](https://www.vimp.com/en/home.html)
- [Mediadrop](https://github.com/mediadrop/mediadrop)
<br>

The goal is to find a video content management system that is:
- open-source/free
- scalable
- ideally has video thumbnail access

**Comment by henrynash** [comment]
This also relates to https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/issues/13 since we would ideally like to allow different CMSs to be plugged in as required by the operator

**Comment by kafellenzer** [comment]
Hello Everyone, 

My name is Kelly Fellenzer and I'm with the RPI RCOS class. Our group is helping work on some of Truth Loop's issues.  Currently, in addition to the CMS options mentioned above our group has found a few other free CMS platforms that would be able to execute Truth Loop's purpose. I was wondering if I could "pick your brains" so to speak to see the current status of this task and determine how our team can contribute to solving this issue.  

Thanks for your time!

KF

**Comment by demilolu** [comment]
@markstur will update this or create new issue.

**Comment by markstur** [comment]
See #13 in regards to making the video server pluggable.

In addition to being able to swap out Watson Media for an open source CMS (in a pluggable way) there should be an easy way for devs and demos.  I think the minimum is to leverage the video that is written to an "uploads" dir and allow that to be sufficient to make the solution fully functional for dev/demo.  Another good option would be to implement w/ S3 and Cloud Object Storage.

It seems like these should have a limit to the number of videos and/or disk space to use.  That could be a separate issue.

**Comment by demilolu** [comment]
still open
