### ISSUE TITLE
Back-end integration testing

### ISSUE THREAD

**Issue by bimsara-yasitha01** [Call-for-Code-for-Racial-Justice/Truth-Loop#97]
We have made a start on integration tests for our back-end routes in [categories.test.js](https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/blob/master/server/routes/categories.test.js) and would like all other routes tested in the same manner. 

These tests use the [SuperTest](https://www.npmjs.com/package/supertest) and [Jest](https://jestjs.io/) frameworks.

**Comment by demilolu** [comment]
Hi @bkgunderson sorry we missed this. We have started some testing which @ed-snodgrass can likely speak more to if you're still interested (beyond Hacktoberfest). cc @upkarlidder

**Comment by ed-snodgrass** [comment]
@bkgunderson I believe you are correct. Although it looks like schema.js is completely commented out so you can probably leave that alone.

**Comment by bkgunderson** [comment]
I will try to find some time & jump back into looking at it. Sorry that I didn't ping it again during Hacktoberfest.
